### ISSUE TITLE
ft-concept-button inverse theme is not correct

### ISSUE THREAD

**Issue by akomiqaia** [Financial-Times/origami#1007]
It seems that in [our demos](https://origami.ft.com/storybook/brands/core/?path=/story/components-ft-concept-button--signup-button&args=theme:inverse) inverse theme does not have a `claret` colour on text and icon. This issue is not present when concept-button is pressed.

**Comment by notlee** [comment]
@akomiqaia Inverse is supported to be white, the claret text and icon is on press:
![Kapture 2023-02-17 at 09 17 46](https://user-images.githubusercontent.com/10405691/219603720-0e69f29c-66a6-4bf5-a7ef-7ea0eb67c817.gif)

**Comment by akomiqaia** [comment]
yeah sorry got confused. Closing because it is not an issue.
