### ISSUE TITLE
Update remaining Origami projects to spec v2 

### ISSUE THREAD

**Issue by notlee** [Financial-Times/origami#107]
Following migrating the following (mostly components) to spec v2: https://github.com/Financial-Times/origami/issues/110

Migrate everything else. Likely this will involve changing the origamiVersion in `origami.json`and nothing else, depending on the project, check workflows and remove any bower references.

**Comment by notlee** [comment]
☝️ before we can complete these component issues, and release betas, we need to [complete this repo data issue](https://github.com/Financial-Times/origami-repo-data/pull/298)

**Comment by notlee** [comment]
[Then go through and update them in order](https://github.com/Financial-Times/origami/issues/110).

**Comment by JakeChampion** [comment]
> ☝️ before we can complete these component issues, and release betas, we need to [complete this repo data issue](https://github.com/Financial-Times/origami-repo-data/pull/298)

This is done now 🎉

**Comment by notlee** [comment]
I've updated this issue to capture upgrading non-components to spec v2

**Comment by JakeChampion** [comment]
This has now been published 🎉  https://registry.origami.ft.com/components/o-autocomplete@1.0.4
