### ISSUE TITLE
Add icons for payment methods.

### ISSUE THREAD

**Issue by notlee** [Financial-Times/origami#11]
Transferring this issue, which was was created and accepted before the proposals board existed:

> To add an icon set for the payment methods on FT.com and potentially elsewhere. By having SVGs in a single place we can ensure consistency going forward and also allows for tinting etc. if need be for various hover states etc when used as button copy.

Original issue: https://github.com/Financial-Times/ft-origami/issues/581
Work in progress: https://github.com/Financial-Times/origami-payment-images/pull/1

**Comment by notlee** [comment]
@rowanmanning if I remember rightly you made progress with this proposal? Do you remember where it was at?

**Comment by rowanmanning** [comment]
Not far, there was a hold up with legal I believe and with James Drayson leaving this work just kind of got dropped. Also the accounts team haven't asked for it again.

**Comment by JakeChampion** [comment]
Since this is over 2 years old (the original issue is in the archived origami repo) and hasn't ever been asked for again, I reckon we should probably close this issue.

@Financial-Times/origami-core, what do you think about closing this issue and archiving the origami-payment-images repo?

**Comment by rowanmanning** [comment]
FWIW I agree with this resolution, this never got picked up after James Drayson left and him and I weren't getting far with legal.
