### ISSUE TITLE
What is the benefit of a distributed component system?

### ISSUE THREAD

**Issue by chee** [Financial-Times/origami#116]
Sub-questions: 
- What is the benefit of other teams being able to create Origami components without the involvement of the Origami team?
- What is the benefit of dynamically generating the list of components from any repository on the Financial Times GitHub, rather than having a defined list of components that we add to manually?
- What is the benefit of the Origami components as a specification, rather than a set of straightforward rules that can be validated with a test suite?
- What is the benefit of treating Origami as a set of definitions (the service spec, the component spec) rather than as a product?

I'm not sure if I've seen this written down anywhere, so would like to be pointed to documentation about it or for answers to this issue to document the answers to these questions.

**Comment by notlee** [comment]
>distributed component system?

Does this question encompass components, tools, and services? I'm assuming yes.

I think there are more negatives than benefits now and we should consider moving to a single repo for components and their tooling, with services in their own repos I think (but that's a more specific conversation). There are opportunities for us to reduce complexity and also decommission some tools and services as a result — e.g. like you hint at in your question, do we need repo data or can we use a list, with shared FT tools like biz-ops to keep track of all the projects we own?

Some benefits of our distributed component system:
- Individual component releases: pros and cons, void now we're moving to npm only and its ecosystem as we can more easily do individual component releases from a mono repo.
- Github issues are contained to a component: maybe a label to filter on would work well enough instead.
- Sense of ownership for non-core maintainers (maybe not a good thing, different teams would ideally feel ownership over and confident contributing to the whole of Origami) 

>What is the benefit of other teams being able to create Origami components?

There are too many components for the core Origami team. Encouraging other teams to build Origami components allows us to share work and expertise, reduce the time we spend repeating work. Even if it's specific to that team to begin with and is later shared more widely and maintenance moved.

>What is the benefit of dynamically generating the list of components from any repository on the Financial Times GitHub, rather than having a defined list of components that we add to manually?

Not a lot outside supporting repos across the FT org/s? Maybe history? That it can be queried? We can get those things with a data stored within the repo.

>What is the benefit of the Origami components as a specification, rather than a set of straightforward rules that can be validated with a test suite?

There isn't? Can everything be tested for? It's useful to point to written rules and (sometimes) track down the reason behind them. To have fewer decisions to make, like how to version a service.

**Comment by chee** [comment]
> > What is the benefit of other teams being able to create Origami components?
> 
> There are too many components for the core Origami team. Encouraging other teams to build Origami components allows us to share work and expertise, reduce the time we spend repeating work. Even if it's specific to that team to begin with and is later shared more widely and maintenance moved.
> 

going to update this question.

What is the benefit of other teams being able to create Origami components without the Origami team being involved?

**Comment by chee** [comment]
> > > What is the benefit of other teams being able to create Origami components?
> > 
> > 
> > There are too many components for the core Origami team. Encouraging other teams to build Origami components allows us to share work and expertise, reduce the time we spend repeating work. Even if it's specific to that team to begin with and is later shared more widely and maintenance moved.
> 
> going to update this question.
> 
> What is the benefit of other teams being able to create Origami components without the Origami team being involved?

However I'd also like to make the point that I think this problem would be better solved the Origami team growing to the point where it would be able to actually support the Origami project

**Comment by chee** [comment]
@notlee is there an easier way than repo data for me to see a list of Origami components that are not maintained by the Origami team?

**Comment by notlee** [comment]
Repo data would be the best way to get a list, otherwise scan the list in the registry for components without the Origami logo: https://registry.origami.ft.com/components?type=component&active=true&maintained=true

**Comment by JakeChampion** [comment]
> * What is the benefit of other teams being able to create Origami components without the involvement of the Origami team?

I reckon the benefit would be autonomy.

I'm going to say not it's not a lot of benefit though. I say that because to my knowledge it has happened less than a 10 times throughout the lifetime of Origami. @wheresrhys might be able to give a better answer as they were around for the start of Origami.

> * What is the benefit of dynamically generating the list of components from any repository on the Financial Times GitHub, rather than having a defined list of components that we add to manually?

I believe this was done because it was a simple system to implement and could be fully automated whereas a list would be manual to keep track of.

> * What is the benefit of the Origami components as a specification, rather than a set of straightforward rules that can be validated with a test suite?

I am not sure what the difference is between a specification and rules.

A non straightforward specification in my opinion is not as good as a straightforward specification but it is better than no specification.

The benefit of a specification is it describes what makes something an Origami component. If a person sees an Origami component, they can know that it implements whatever the specification states. You would get the same benefit with rules, which is why I am not sure on the difference between a specification and rules.

> * What is the benefit of treating Origami as a set of definitions (the service spec, the component spec) rather than as a product?

The only benefit I can come up with for this would be, people from outside of Origami could build services and/or components which follow the specification.

**Comment by wheresrhys** [comment]
FYI, on the 'get a component list' question, in Q2 rel-eng are almost certainly gonna work on getting package <-> repo mappings into Biz Ops

**Comment by chee** [comment]
> The benefit of a specification is it describes what makes something an Origami component. If a person sees an Origami component, they can know that it implements whatever the specification states.

I think the specification is too complicated and has too many "may" and "should" for this to be the case.
By rules I meant something more akin to a small API and lifecycle definition. Something that a person could hold in their head, something that a test suite could verify.
