### ISSUE TITLE
Licence badge doesn’t link to a valid section

### ISSUE THREAD

**Issue by robinwhittleton** [Financial-Times/origami#118]
Hi FT 👋 I was reviewing common licences that design systems use. Nice that you’ve got a badge in README, but it links to `#licence` that doesn’t exist. Could you add the section or remove the link?

**Comment by JakeChampion** [comment]
Thanks for the issue, this has been fixed in https://github.com/Financial-Times/origami/commit/60c95fbd8a921f3c8cc61994c41bc32c55c1e0c8
