### ISSUE TITLE
Origami v2 Migration Guides

### ISSUE THREAD

**Issue by chee** [Financial-Times/origami#122]
## build service v2 to v3 migration
- Put your current URLs into the URL Updater
- Use the new v3 URL (make sure you have a system-code and an explicit brand!)

## npm to npm migration
- Update your package.json to point at the new major versions of all your components
- Remove `is-origami-flat` and `lockspot` from any postinstall or postshrinkwrap scripts
- If everything is broken, maybe try deleting your `package-lock.json` and trying again

**Comment by JakeChampion** [comment]
This work has been completed 🎉 it's on this page --> https://origami.ft.com/blog/2021/07/01/origami-on-npm-and-how-to-migrate/#migration-guides
