### ISSUE TITLE
Rollout majors

### ISSUE THREAD

**Issue by notlee** [Financial-Times/origami#128]
_Note: I couldn't think of a great place for this issue. It's
not a component, not a proposal, and projects can't have issues.
See project: https://github.com/orgs/projects/77._

**Publish the new major of each component,
updating dependencies including demo dependencies along the tree**

Components in each step have at least one dependency on
the component in the previous step. Not all components in 
a step have to be completed before starting work on the next 
step because each component doesn't depend on everything
from the previous step.

**Tasks**
- Pick a component below and check it, so we don't work on the same component. 
- Checkout the `breaking` branch (they should mostly be named breaking but may be different, some components noted below have a WIP `upgrade-dependencies` branch )
- Update `bower.json` with the latest major versions (with caret semver range 🥕 )
  - If the component has dependencies which were also bumped, add a note to the migration guide to explain this. Template:
      ```
      #### Updated dependencies

      The dependencies for this component have all been updated to the latest major versions.
      If you have any conflicts while installing this version, you'll need to first update
      its dependencies. See [the Bower config for these](./bower.json).
      ```
- Update `origami.json` demo dependencies with the latest major versions (with caret semver range 🥕 ). If the demo dependency hasn't been released yet then bump the version to the new major speculatively, so the demos work in the registry when the new dependency major is released (e.g. o-colors demos depend on o-buttons, causing a circular dependency). Keep in mind not all dependencies have a new major version though (o-spacing for examples).
- Complete any outstanding component upgrades (see note against components below)
- Scan the public interface, Sassdoc, README, MIGRATION -- does everything look good?
- PR the changes against the `breaking` branch for approval.
- Merge the breaking PR (please do a rebase merge to preserve the history) and release a major version.

Step 1 of migration:
- [x] o-utils
- [x] o-autoinit
- [x] o-colors
- [x] o-date
- [x] o-errors
- [x] o-fonts
- [x] ftdomdelegate
- [x] o-grid
- [x] o-lazy-load
- [x] o-toggle
- [x] o-viewport

Step 2 of migration:
- [x] o-tracking
- [x] o-normalise
- [x] o-icons
- [x] o-ft-affiliate-ribbon
- [x] o-gallery
- [x] o-loading
- [x] o-share
- [x] o-syntax-highlight
- [x] o-typography
- [x] o-visual-effects

Step 2b of migration:
- [x] o-buttons

Step 3 of migration:
- [x] o-big-number
- [x] o-editorial-typography
- [x] o-expander
- [x] o-banner
- [x] o-tabs 
- [x] o-header
- [x] o-header-services
- [x] o-message
- [x] o-table 
- [x] o-forms
- [x] o-video
- [x] o-footer
- [x] o-footer-services
- [x] o-labels
- [x] o-layout
- [x] o-quote
- [x] o-stepped-progress
- [x] o-teaser-collection
- [x] o-overlay

Step 4 of migration:
- [x] o-editorial-layout
- [x] o-cookie-message
- [x] o-topper
- [x] o-teaser
- [x] o-tooltip

**Comment by JakeChampion** [comment]
I think this is done now?

**Comment by notlee** [comment]
SO DONE
