### ISSUE TITLE
Proposal: Reorganise Origami's Slack presence 

### ISSUE THREAD

**Issue by chee** [Financial-Times/origami#130]
A few years ago, Origami was more open than it is now.

Part of this, I think, is rooted in the fact that most of the conversation about Origami's products and services by the members of the team happens behind closed doors, in a private Slack channel.

Origami is a team that is primarily a service-provider for other teams, everything is open source, and I'm proposing that this project-relevant chat should be in the open too.

### `#origami`

This new channel is where we'll have discussions as a team that are related to the work we do. Conversations about polyfill.io, components, the origami- services will take place here in the open where anyone can read them and even contribute if they feel comfortable doing so. Most of the conversations that currently happen in `#`:lock:`origami-internal` will happen here instead.

### `#origami-support` (formerly known at `#ft-origami`)

What is currently `#ft-origami` will be renamed to `#origami-support`. That's what we'll have in the footers of our website, and that's what we'll list as the support contact for our components and services.
We can enable notifications on this channel if we like, and the conversations there are started by people who need our help

### `#`:lock:`origami-internal`

It's important for us still to have a channel that's private from our stakeholders, where we can speak openly to each other about things that impact us as people. Also where we can coördinate lunches and WFH and holidays and so on.

**Comment by notlee** [comment]
It's unfair to characterise our current workflow as conversions in a cathedral. We have project relevant discussions within issues and advertise them in`#ft-origami` to encourage wider contributions where relevant -- like when we decided to [remove custom class names](https://github.com/Financial-Times/origami-proposals/issues/4). 

This is a good idea though, especially so people can see and join in on other chat -- like what Jake shared yesterday about the person who got polyfill.io on CloudFlare Workers 😊

**Comment by chee** [comment]
Not all of our conversations, that's true. Some of it happens on issues. But most of that chat happened in the private channel first, and some of it was moved to issues. Sometimes the issue says "we discussed this privately and decided against it".

Having the discussions in private and then making the result open is what a cathedral is, though, in terms of the "The Cathedral and the Bazaar" thing written by worst-person-on-earth-contender Eric Raymond.

The Bazaar is open development where every commit and conversation happens in the open, and the Cathedral is when you do the work and decision-making in private and then release the result of that. And I'm not saying our whole development process is a cathedral, just the conversations in #origami-internal that are then announcements. Maybe it's something easier to notice as someone who has until recently not been privy to #origami-internal, i don't know.

But in the interest of not getting into a side-conversation about the word _cathedral_, I'll remove it from the proposal and replace it with some clearer language.

**Comment by rowanmanning** [comment]
I'm keen on this proposal 👍 great work. I'm in favour of implementing exactly as outlined here, but would like to make sure nothing breaks at the same time with the channel rename (like I think we might need to do a small amount of [Repo Data](https://github.com/Financial-Times/origami-repo-data) work)

**Comment by JakeChampion** [comment]
I pledge my support for this proposal

**Comment by chee** [comment]
@rowanmanning oh! i can volunteer to do the repo data work, what’s involved there?

**Comment by rowanmanning** [comment]
The repo has a lot of [instances of `#ft-origami`](https://github.com/Financial-Times/origami-repo-data/search?q=ft-origami&unscoped_q=ft-origami) like most of our components/services, but the most important replacement is [the default Slack channel we use](https://github.com/Financial-Times/origami-repo-data/blob/44f92e8cc8046ec5479aecc820d91cdf9aa1d118/models/version.js#L714) if the manifest doesn't have one.

We'd probably also need to write a new [database migration](https://github.com/Financial-Times/origami-repo-data/tree/master/data/migration) to replace the old Slack channel name in all of the entries in the `versions` table. There are some [instructions in the README](https://github.com/Financial-Times/origami-repo-data#database) for this but happy to help if I can.

All this work probably needs to be merged already on the QA dynos, then promoted to production soon after we change the channel name. It's possible a lot of it is handled by Slack redirects but I'm not 100% on that

**Comment by chee** [comment]
We did it!
