### ISSUE TITLE
Proposal: Replace the word `component` in the manifest spec when it isn't being used to refer to components

### ISSUE THREAD

**Issue by chee** [Financial-Times/origami#149]
The [component spec](https://origami.ft.com/spec/v1/components/) and the [services spec](https://origami.ft.com/spec/v1/services/) only use the word "component" to refer to our front-end components. 

The manifest spec uses the word "component" to refer to services, components and all other origami projects.

I propose changing the word `component` to the word `project` in places where it isn't being used to refer to components.

```diff
-Defines the type of Origami component that the manifest belongs to. Must be set to one of:
+Defines the type of Origami project that the manifest belongs to. Must be set to one of:
```

etc

**Comment by notlee** [comment]
I approve this message -- death to "module"

**Comment by chee** [comment]
@notlee eventually!! for now we'll use `component` to refer only to components and then next time we can change `module` to `component` and finally we'll all be able to rest

**Comment by rowanmanning** [comment]
Yeah very happy with this

**Comment by JakeChampion** [comment]
Yes please
