### ISSUE TITLE
Bullet points don't line up with text

### ISSUE THREAD

**Issue by sjparkinson** [Financial-Times/origami#169]
## What

Bullet point dots don't _quite_ line up with the text.

Chrome on macOS.

![image](https://user-images.githubusercontent.com/51677/58038918-3388f500-7b29-11e9-8278-138898b13913.png)

## Details

See https://customer-products.in.ft.com/wiki/Developer-Overview#conventions for an example. And maybe related to Financial-Times/o-layout#22.

**Comment by JakeChampion** [comment]
This looks like it was fixed at some point, I checked in safari, chrome and firefox and all looked to have correct alignment 
![screenshot of the o-layout documentation demo in chrome, safari, and firefox which shows the bullet points are aligned correctly with the bulleted text](https://user-images.githubusercontent.com/1569131/152825502-6dae79ae-7ece-43a2-a960-a098b70f9232.png)

**Comment by chee** [comment]
@JakeChampion nice! bullet points line up with text!
