### ISSUE TITLE
feedback component

### ISSUE THREAD

**Issue by notlee** [Financial-Times/origami#19]
## What

A component to display a feedback call to action, which can link to feedback input or display a feedback overlay in-page. I imagine the content of the feedback overlay will be up to the user.

## Why / Supporting Examples

The FT has a feedback tab [n-feedback](https://github.com/Financial-Times/n-feedback) which opens an overlay with form input:
<img width="1421" alt="Screenshot 2020-01-30 at 11 54 46" src="https://user-images.githubusercontent.com/10405691/73665116-7c251600-4698-11ea-8aea-1bb644cbb354.png">

So does fdi:
<img width="1443" alt="Screenshot 2020-02-03 at 15 20 19" src="https://user-images.githubusercontent.com/10405691/73665252-b4c4ef80-4698-11ea-9f65-e7987585078f.png">

Spark has a feedback button in the header. Speaking to Jessica and David, we think this could follow the same pattern instead:
<img width="1421" alt="Screenshot 2020-01-31 at 14 29 40" src="https://user-images.githubusercontent.com/10405691/73665332-d0c89100-4698-11ea-9340-9a1c8da886d8.png">

Which other internal tools, that gather feedback from the header also but in a slightly different way, could perhaps use too (see inside header and o-message below header):
<img width="1421" alt="Screenshot 2020-01-30 at 11 54 18" src="https://user-images.githubusercontent.com/10405691/73665371-e2aa3400-4698-11ea-9ec7-69662938a3f5.png">

**Comment by chee** [comment]
https://github.com/Financial-Times/origami/pull/98
