### ISSUE TITLE
Proposal: perform a review of the Origami spec

### ISSUE THREAD

**Issue by rowanmanning** [Financial-Times/origami#20]
Proposing that we perform a review of the Origami spec, with the aim of deciding whether we're due an iteration of it.

There are several issues with the Origami spec, and we'd like to better understand some of the decisions that were made between 2013 and now. Please add to the lists below whenever you find something in the spec that doesn't make sense, or is confusing/irritating.

- The `origamiType` for what we know as a front-end component is actually `module`. This no longer correct
- The support information for a component is disparate, as when the spec was created the `support` field was free-text, allowing you to add a URL, email address, or whatever you wanted

**Comment by chee** [comment]
i'm moving this to the `origami` board because until we have a unified proposals board, that's where proposals like this continue to live

**Comment by chee** [comment]
I think this is covered by #86 :D
