### ISSUE TITLE
Introduce a Ghost button style.

### ISSUE THREAD

**Issue by notlee** [Financial-Times/origami#252]
**Requested by James [here](https://github.com/Financial-Times/o-buttons/issues/183).** 
> Introduce a Ghost button style for Masterbrand, Mono and Inverse themes. I've got an alternative version for the Masterbrand as it would be good to check accessibility of both options.

**Example usecase on Loadstar (default / hover):**
<img width="244" alt="screenshot 2019-01-25 at 10 39 07" src="https://user-images.githubusercontent.com/10405691/51740975-795b1280-208d-11e9-8bb0-f459d7b2ed1a.png">
<img width="253" alt="screenshot 2019-01-25 at 10 39 11" src="https://user-images.githubusercontent.com/10405691/51740976-795b1280-208d-11e9-9134-91c20c7699d7.png">

**Comment by chee** [comment]
If this is adding a new button, why would it need to be part of a major?

**Comment by notlee** [comment]
Design ready for review here:
https://www.notion.so/prd-newsroom/f33e3bf32fd74c46900cb967665647a4?v=f1f902cd49ed418ab3eb02d33a24c158

**Comment by JakeChampion** [comment]
> Design ready for review here: [notion.so/prd-newsroom/f33e3bf32fd74c46900cb967665647a4?v=f1f902cd49ed418ab3eb02d33a24c158](https://www.notion.so/prd-newsroom/f33e3bf32fd74c46900cb967665647a4?v=f1f902cd49ed418ab3eb02d33a24c158)

Design has been approved, it is now ready for an implementation in Origami

**Comment by JakeChampion** [comment]
This was added in https://github.com/Financial-Times/origami/pull/642
