### ISSUE TITLE
Send out a survey to our customers

### ISSUE THREAD

**Issue by chee** [Financial-Times/origami#29]
Let's ask our customers what we should be working on.

Questions like:

```
How many apps do you maintain?
How many of those use origami components?
How many of those use the build service?
How many of those use the image service?
How many of those use the polyfill service?
```

What else should we ask? Who should we ask? How do we ask them? When?

**Comment by rowanmanning** [comment]
Hey, sorry for the delay, here are my thoughts:

## Format

I think it should be a Google Form as Jake suggests. We should send it both in a newsletter and via Slack, with a few separate prompts. Maybe we run it for a couple of weeks?

I'm considering whether we're more likely to get engagement if we send very short (like two questions) surveys more frequently (like once each planning cycle). It would mean that we might get more responses to the questions which matter to us most, based on what came out of planning.

## Questions

Based on what we're aiming to get done this planning cycle, I think we should focus questions on one or two things. Possibly white-labelling of components, and getting other teams to build components.

**Comment by JakeChampion** [comment]
> I think it should be a Google Form as Jake suggests. We should send it both in a newsletter and via Slack, with a few separate prompts. Maybe we run it for a couple of weeks?

Yes!



> I'm considering whether we're more likely to get engagement if we send very short (like two questions) surveys more frequently (like once each planning cycle).

Yes!


> Based on what we're aiming to get done this planning cycle, I think we should focus questions on one or two things. Possibly white-labelling of components, and getting other teams to build components.

Yes, these two are likely a good start :-)

**Comment by rowanmanning** [comment]
We sent one!
