### ISSUE TITLE
Proposal: Continuous delivery

### ISSUE THREAD

**Issue by JakeChampion** [Financial-Times/origami#30]
## What
Currently our projects which get published to a registry such as npm/bower are done in multipel ways:

- Completely manual process -- Developer runs `npm version` `npm publish` on their machine
- Partially automated -- Developer adds a git tag and pushes tag to GitHub, which triggers `npm publish` on CircleCI or GitHub Action
- Fully automated -- Developer uses specific commit format which declares what the next version will be and CircleCI or GitHub action runs `npm version` `npm publish`

A consistent approach to versioning and publishing would be very useful to have, I think we should also look to automate the process as to make releases happen often and make them as painless as possible.

I would like to propose a system which uses GitHub labels to mark what the pull-request change is (`major`/`minor`/`patch`). The system will be opt-in, which will allow us to carry on our current workflows and slowly migrate to the new automated workflow on a pull-request by pull-request basis.

The benefits of an automated approach:
- Making new releases for previous major versions will "just work". With our manual and partially automated approaches, we have made releases to the wrong version a few times.
- Releasing happens faster (we have some projects which have many changes in master which have not been released yet. I.E. origami-build-tools and the other less worked on projects).
- We can add extra features/protections to the versioning, such as enforcing a migration guide exists if the label added was `major`.

### Pull-Request merged without a SemVer label

1. Comment on the pull-request and say it will not be released automatically

#### Pull-Request merged with a SemVer label

1. Find the current version (package.json or by looking for the first SemVer tag when traversing parent commits)
2. Increment the version based upon the SemVer label on the pull-request
3. Create a git tag which corresponds with the new version

**Comment by chee** [comment]
if it's done using a github action, after the comment came in saying "you didn't add a label" you could add the label to the already merged PR and click "rerun workflow"

**Comment by JakeChampion** [comment]
@rowanmanning what do you think to this proposal?

**Comment by rowanmanning** [comment]
I think this is a great proposal! Sorry for the delay in commenting here, but I'm excited by it and think we should do this 🙂 I know we spoke about it in the last Office Hours, and I think your approach is great.

**Comment by chee** [comment]
if we merge in 3 `major` labels in a short time (like, if we've gathered a few breaking changes to o-table over a few months and then we do a major), are we going to go up 3 major versions on that component?

**Comment by JakeChampion** [comment]
> if we merge in 3 `major` labels in a short time (like, if we've gathered a few breaking changes to o-table before we're ready to do a major), are we going to go up 3 major versions on that component?

If they 3 merges are all to master, then yes.

The way I've seen us work when making new majors with lots of changes is we make a new branch called `vX` where X is the new major version number. We branch from `vX` and make many small pull-requests with the breaking changes and when we have finally done them all, we open a pull-request from `vX` to `master`. If we wanted to use the automated versioning system, we would only label the pull-request `vX` to `master` as `major` and not the others.

**Comment by JakeChampion** [comment]
Here is the GitHub Action I've been working on which implements this proposal -- https://github.com/Financial-Times/origami-version/

**Comment by notlee** [comment]
Can this be closed now @JakeChampion ? :)
