### ISSUE TITLE
Move our env vars to vault

### ISSUE THREAD

**Issue by chee** [Financial-Times/origami#31]
At the moment some of our env vars are in vault, and others are in LastPass. We should put them all in vault so we can automate more:)

**Comment by rowanmanning** [comment]
We have an [SRS ticket for Q2](https://financialtimes.atlassian.net/browse/SRS-121) which is related to this now, just so our security work is helping move that needle 🙂

**Comment by chee** [comment]
i'm currently not actively working on this btw.

i'll need to actually make a schedule for next week because i'm all over the place at the moment!

**Comment by chee** [comment]
i'm working on this today

**Comment by chee** [comment]
done
