### ISSUE TITLE
Verify component demos have valid html

### ISSUE THREAD

**Issue by notlee** [Financial-Times/origami#328]
The build service throws an error rather than return invalid html from the html endpoint. However we do not
have the same check when working on components locally. For example o-header@9.0.2 has invalid demo
markup, which was not caught by tests.

![Screenshot 2021-09-28 at 11 26 50](https://user-images.githubusercontent.com/10405691/135070368-12a6eb70-1700-4e89-91a6-c87384df2be8.png)

**Comment by chee** [comment]
yes!
