### ISSUE TITLE
Proposal: allow a type of `component` in `origami.json`

### ISSUE THREAD

**Issue by rowanmanning** [Financial-Times/origami#35]
## What

Allow `origamiType` in an an Origami manifest to be `component`.

## Why

As we've acknowledged already, an `origamiType` of `module` is confusing to us. We've updated the spec to stop calling everything a component, choosing project instead. Maybe rather than waiting for an overhaul of the spec, we should allow _both_ `component` and `module` to describe a component and update our tooling to convert them.

## How

We'd need to update Repo Data in advance, and possibly then update Registry UI to send a `component` query parameter instead of `module`. This wouldn't be required though as Repo Data would need to support both until we do a major bump of it's API.

Then we could update component manifests as-and-when we need to.

**Comment by notlee** [comment]
This sounds good to me, if we support both. I can't think of any other system outside repo data / registry ui that relies on this.

**Comment by rowanmanning** [comment]
Oh I guess also @chee's work on manifest validation too

**Comment by JakeChampion** [comment]
I am in favor of this proposal 👍

**Comment by chee** [comment]
i'm in favour of this!!

**Comment by JakeChampion** [comment]
This work has been done 🎉 

https://github.com/Financial-Times/origami-website/pull/202
