### ISSUE TITLE
Make sure that CyberSecurity has some oversight on Cloudinary

### ISSUE THREAD

**Issue by rowanmanning** [Financial-Times/origami#38]
We looked into putting OKTA in front of Cloudinary, but it costs more money and probably doesn't represent a large enough risk to take on.

However CyberSecurity would like to make sure that it's on their compliances radar. We need to speak to Mary Williamson about this, [ticket here](https://financialtimes.atlassian.net/browse/SRS-120).

**Comment by JakeChampion** [comment]
Had meeting with CyberSecurity, our manual leavers process is enough to satisfy them with regards to the security of our use of Cloudinary
