### ISSUE TITLE
Proposal: move all of Origami's automated testing to GitHub Actions

### ISSUE THREAD

**Issue by rowanmanning** [Financial-Times/origami#39]
## What

We currently use CircleCI for all of our linting and automated testing. I'm proposing that we move all of this stuff to GitHub actions instead.

## Why

We've been using GitHub Actions more and more, and they're really powerful. As well as being able to trigger actions on many different repo events, they're also easily shareable – you create an action repo and that can be used immediately by any other repo.

@edds also looked into [CircleCI usage and queue time](https://docs.google.com/spreadsheets/d/1wyaQsI_EBWXN0vQ6YRiTtYwaMOvuValWt3IjyEa-sr0/edit), which seems to be increasing. I think moving all of our stuff to GitHub actions might help to ease this, especially as we frequently make changes across 90+ repositories.

## Supporting Examples

We have a few actions already:

  - **[origami-project-board-action](https://github.com/Financial-Times/origami-project-board-action):** Add new issues and pull requests to Origami Project Board
  - **[origami-version](https://github.com/Financial-Times/origami-version):** create semver git tags and release based on PR labels
  - **[origami-labels](https://github.com/Financial-Times/origami-labels):** sync a repo's issue labels with the standard Origami set

**Comment by JakeChampion** [comment]
Here is an example of how an Origami Component would be on GH https://github.com/Financial-Times/o-visual-effects/pull/37

**Comment by JakeChampion** [comment]
If we like the above approach then I can roll that out to all components and do another approach for services and CLIs etc :-)

**Comment by JakeChampion** [comment]
One amazing benefit to this is the fact that a GH Action can report inline on the PR with issues/comments. This would be great for obt verify and the spec verification work Chee is doing.

Example of GH Action making comments -- 
<img width="1435" alt="Screenshot 2020-04-02 at 12 51 59" src="https://user-images.githubusercontent.com/1569131/78246249-c41db900-74e0-11ea-9c7d-ce5a736c93fb.png">
https://github.com/Financial-Times/oax/pull/34/files#diff-af0c9064fad623e4bdfe3a03a7b9bfaeR201

**Comment by JakeChampion** [comment]
This is now done :-)
