### ISSUE TITLE
Add new tool to verify the readme of components is valid

### ISSUE THREAD

**Issue by JakeChampion** [Financial-Times/origami#403]
This is part of a bigger piece of work on deconstructing origami-build-tools into smaller isolated tools -- https://github.com/Financial-Times/origami/issues/402

I think the verify readme task could be replaced with a tool which runs [remark-cli](https://www.npmjs.com/package/remark-cli) within the components folder, using the components `.remarkrc.cjs` configuration

The code within origami-build-tools for the existing verify readme task is located here -- https://github.com/Financial-Times/origami/blob/595aca7158ce80f271c445211c9b666a8f582617/tools/origami-build-tools/lib/tasks/verify-readme.js

**Comment by chee** [comment]
closed in #409
