### ISSUE TITLE
Survey: how can we better support specialist?

### ISSUE THREAD

**Issue by rowanmanning** [Financial-Times/origami#41]
We need to write a survey to help us understand how we can better support Specialist Titles. This will help guide our next steps on the whitelabel brand and whether we should allow more customisation of Origami components.

We decided to send multiple more focused surveys in #29, and to make surveys a more regular thing.

**Comment by rowanmanning** [comment]
@notlee and I have brainstormed some questions. We think we should make this dual-focused:

1. Understanding the level of Origami expertise within Specialist
2. Finding out how we can help

Some draft questions:

1. How familiar are you with Origami and what the team does? [1–5]
1. How often do you use Origami components or services as part of your work?
    a. I'm not sure
    b. Never
    c. Monthly or less frequently
    d. Weekly
    e. Most days
1. What parts of Origami do you use? [multi]
    a. I use some Origami components
    b. I use some Origami services
    c. TODO more please, or more granular
    d. Other [free-text]
1. If you had an issue with an Origami component or service, or wanted to discuss a new feature, what would you do? [free-text]
1. Do you think the work that Origami does is relevant to Specialist? [1–5]
1. Is there anything Origami could do which would make your work life easier on Specialist? [free-text]
1. Optional name

**Comment by JakeChampion** [comment]
I've started creating the survey, please have a look though and let me know what you think @chee and @notlee -- https://docs.google.com/forms/d/1Bu4RaIb4dRge2TIBUt1eLtb71VBsnohMJ3ikZLbUAIg/edit

**Comment by JakeChampion** [comment]
This survey has been sent out

**Comment by JakeChampion** [comment]
We got 3 responses, Specialist believe Origami is relevant (woohoo!). As we are currently a smaller team than usual we will have to put this work on directly helping Specialist back on the backlog. The work we are already doing on improving the development process and guides for creating new Origami Components, should also help Specialist.
