### ISSUE TITLE
Add a GitHub action to add `origamiType` labels to a new issue or pull request

### ISSUE THREAD

**Issue by notlee** [Financial-Times/origami#43]
So we can filter issues in our project board by component.

See Origami-Type Labels
https://github.com/Financial-Times/origami-labels#origami-type-labels

We decided to map the `module` type to a `component` label, as we refer
to the modules type as components in reality.

Eventually `module` will be replaced with `component` behind 
the scenes too. https://github.com/Financial-Times/origami-repo-data/pull/139

**Comment by JakeChampion** [comment]
when we decide to work on this GitHub Action, the [Origami Percy GitHub Action](https://github.com/financial-times/origami-percy) would be good to look at as it does similar things, it reads origami.json file and removes a label, very close to the features we will be wanting to use :slightly_smiling_face:

**Comment by notlee** [comment]
See https://github.com/Financial-Times/origami-apply-labels/

**Comment by JakeChampion** [comment]
looks good!
