### ISSUE TITLE
Write and send Q2 2020 Surveys

### ISSUE THREAD

**Issue by rowanmanning** [Financial-Times/origami#46]
This issue is used to track our progress towards sending three Origami user surveys in Q2 2020. Surveys should be opened as separate issues, this one is used mostly as a progress bar.

- [x] [Why don't people build Origami components?](https://github.com/Financial-Times/origami/issues/40)
- [x] [How can we better support specialist](https://github.com/Financial-Times/origami/issues/41)
- [x] TBC

**Comment by JakeChampion** [comment]
What other surveys should we be sending out in Q2?
Do we want a survey for the Origami Build Service users, to see if we should be working on a v3 and what we should be looking to change/add to the service?

**Comment by JakeChampion** [comment]
We don't have capacity to do more surveys and act on their feedback due to being at 75% of our normal team size
