### ISSUE TITLE
Make a GitHub template repository for an Origami component

### ISSUE THREAD

**Issue by rowanmanning** [Financial-Times/origami#49]
## What

We should have a GitHub template repository for an Origami component which is kept up to date.

## Why

This will speed up component development, as new components can be created based on the template repository.

**Comment by chee** [comment]
i started working on this, but i think maybe it would be better to improve `obt init` instead. (or, as @apaleslimghost recommended a `npm init origami-component` script)
some prior work for an interactive obt init was done here by gabi: https://github.com/Financial-Times/origami-authoring-tools/blob/e8db36eb73e2146e9cf4c7193b97c8daed98f7c4/src/prompts/boilerplate.js

here's why:

If we set the `origamiType` to `template` then that will be something the user needs to change once they've forked the repo, if we set the `origamiType` to module then it will appear as a component in the registry

so either we have that in the repo, or we add another item to the list of things they need to do (and could easily miss) when using the template repo.

1. set correct name in bower.json
2. set correct name in package.json
3. set correct origamiType
4. set correct keywords

etc. etc.

it would be nice if instead we had an interactive component initializer, and then maybe the default demo can provide some helpful instructions to them for what to do next:)

**Comment by notlee** [comment]
What I like about creating a github template is that we can update it when we mass update all our components. We often forget to update `obt init`. 

Maybe we could have a component template in Github which `obt init` uses? `obt init` could update `bower.json`, find and replace the example component name, etc.

**Comment by chee** [comment]
hmm, if we forget to update `obt init` then what stops us from forgetting to update the template?

**Comment by chee** [comment]
https://github.com/Financial-Times/origami-authoring-tools

**Comment by rowanmanning** [comment]
☝️ In Office Hours we agreed that we should resurrect the part of oax that creates a boilerplate component. This means we get the most for the least amount of work (hopefully)

**Comment by JakeChampion** [comment]
The new repo for this work is https://github.com/Financial-Times/create-origami-component/

**Comment by chee** [comment]
i think this issue has done its duty, we have new issues open for the things that relate to the `create-origami-component` tool
