### ISSUE TITLE
Does o-layout interfere with o-message icons?

### ISSUE THREAD

**Issue by wheresrhys** [Financial-Times/origami#491]
Fairly consistently o-message icons get misaligned when using with o-layout. Happens with normal and inner messages when copy and pasting the markup straight from the registry demo. 

Is there some kind of interference between the two components

![image](https://user-images.githubusercontent.com/447559/147826603-c674c84f-26b0-4eed-ab16-d5cb85a345f1.png)

**Comment by notlee** [comment]
@wheresrhys do you have example markup we could look at? o-layout shouldn't interfere with other components. Off the top of my head you might want to check there isn't the `o-layout-typography` class on a parent element which is a common mistake – that will interfere with child components and should only be used to wrap blocks of typography elements.

https://registry.origami.ft.com/components/o-layout@5.2.0/readme?brand=core#typography

**Comment by wheresrhys** [comment]
There is a wrapper with o-layout-typography, but the message and the message container both have o-layout__unstyled-element. Shouldn't that avoid this issue?
```html
<div class="o-layout-typography hub-content"><div class="o-layout-item o-layout__unstyled-element">
      <div class="o-layout__unstyled-element o-message o-message--alert o-message--inner o-message--success" data-o-component="o-message">
        <div class="o-message__container">
          <div class="o-message__content">
            <p class="o-message__content-main">
              <span class="o-message__content-highlight"> Success! </span>
              spring-framework-3-2-eol has been marked as complete by engineering-insights
            </p>
            <p class="o-message__content-additional">
              To undo this visit <a href="https://biz-ops.in.ft.com/Team/engineering-insights/edit?properties=completedTechnologyLifecycleEvents">your team page in Biz Ops</a> and remove any you want from the list.
            </p>
          </div>
        </div>
      </div>
   </div></div>
   ```

**Comment by notlee** [comment]
`o-layout__unstyled-element` would need to be applied to _every_ child element, it's not a practical approach for components. It can be useful if you have, say, one or two button elements within a block of text

**Comment by notlee** [comment]
Hey @wheresrhys, I'm looking to close this issue, does that help?
