### ISSUE TITLE
Autocomplete

### ISSUE THREAD

**Issue by notlee** [Financial-Times/origami#5]
## What

A component to allow search/filtering of a dataset with "suggested search" autocomplete behaviour. A common use is in search bars but could apply to other contexts.

## Why

Laura C has requested autocomplete for internal products. O&R have requested autocomplete. It has also been requested directly by multiple people/teams in #ft-origami over the years. More recently Elena's team have one based loosely on the MyFT one, and Joanna has asked for autocomplete suggestions in the engineering channel "We’ve got a dataset of 2 million rows, and we’d like to build a search/autocomplete service around it.".

## Supporting Examples

ip-people:
<img width="851" alt="screen shot 2018-07-31 at 10 54 28" src="https://user-images.githubusercontent.com/10405691/47083750-7ab4ad80-d209-11e8-881f-c7cdb6d39dc0.png">

myft:
<img width="1186" alt="screen shot 2018-10-17 at 12 45 52" src="https://user-images.githubusercontent.com/10405691/47084156-9f5d5500-d20a-11e8-9075-a01185e1ba7e.png">

ft.com/graphics:
<img width="1232" alt="screen shot 2018-10-26 at 15 36 39" src="https://user-images.githubusercontent.com/10405691/47576741-26ae7500-d93d-11e8-8e1a-c24a4d6d5c88.png">

**Comment by notlee** [comment]
Another example when creating a health check via biz-ops. Currently uses awesomecomplete.

<img width="470" alt="screen shot 2018-11-14 at 12 59 33" src="https://user-images.githubusercontent.com/10405691/48484203-6fa36c00-e80d-11e8-8b38-cc5192fcf276.png">

**Comment by GeoffThorpeFT** [comment]
Its worth noting that an autocomplete could be connected to a static or dynamic dataset.
Static datasets (or those datasets which are rarely updated) could be connected and populated at build time (thus removing the need for a permanent connection back to the raw data at runtime). Whereas the dynamic sets would need to retain a connection to data which may only be accessible through authentication.

**Comment by gvonkoss** [comment]
A UX reference of ['rules' for autocomplete](http://jeremymikkola.com/posts/2019_03_19_rules_for_autocomplete.html).

**Comment by notlee** [comment]
Looks like cloud enablement also uses an autocomplete like interface

<img width="1355" alt="Screenshot 2019-04-26 at 11 17 31" src="https://user-images.githubusercontent.com/10405691/56801351-2839f680-6815-11e9-993a-726e3c3d865b.png">

**Comment by notlee** [comment]
We just discussed in our open meeting and think there's definitely a strong case for this component, and it something we intend to add 🎉

**Comment by notlee** [comment]
Another auto-complete like component but for creating tags (thanks to Jono for tracking these down a little while ago now):

TagMe:
<img width="446" alt="Screenshot 2019-05-31 at 12 07 42" src="https://user-images.githubusercontent.com/10405691/64521145-5c5b1300-d2ef-11e9-9431-a5be48f46a7d.png">

Graphics hub:
<img width="442" alt="Screenshot 2019-05-31 at 11 47 35" src="https://user-images.githubusercontent.com/10405691/64521164-6846d500-d2ef-11e9-9e18-ba3d7cd12485.png">

Biz ops:
<img width="630" alt="Screenshot 2019-05-31 at 11 58 27" src="https://user-images.githubusercontent.com/10405691/64521158-641ab780-d2ef-11e9-8328-7433d140f0f7.png">

Enterprise tools:
<img width="621" alt="Screenshot 2019-05-31 at 11 45 32" src="https://user-images.githubusercontent.com/10405691/64521201-7eed2c00-d2ef-11e9-980b-3c321a11c0f7.png">

Loadstar:
![image](https://user-images.githubusercontent.com/10405691/64521218-8a405780-d2ef-11e9-8627-19ee1b605069.png)

**Comment by adgad** [comment]
We have a use case for something similar in Spark. When search Fotoware for images, our users want to easily search for multiple combined search terms (like "Donald Trump" "Boris Johnson"), without having to use quotes or fancy syntax. In Fotoware, this is done by adding search terms as tag-like things by pressing enter. We've replicated something like that in Spark. In our case, it's not from a known set of terms, so there's no autocomplete required.

<img width="477" alt="Screenshot 2020-02-07 at 14 20 11" src="https://user-images.githubusercontent.com/1978880/74038818-accabf80-49b8-11ea-9840-71d959d1bacd.png">

**Comment by rowanmanning** [comment]
I've created a [new proposal](https://github.com/Financial-Times/origami/issues/42) for tag inputs. The interface for adding multiple tags _can_ use an autocomplete, but won't be built as _part_ of an autocomplete component.

**Comment by nickcolley** [comment]
I have worked on maintaining this project: https://github.com/alphagov/accessible-autocomplete

Autocomplete is very complicated to get right, my main recommendation would be to try to make sure the results are separate from the interface itself.

So you have an 'engine' like a search engine, which is responsible for taking the input and outputting useful results.
An example of this might be in a country picker, determining that 'GB' means Great Britain.

This 'engine' can be separated from the actual interface aspects of the component itself, and I think that way allows you to reduce the scope of an already very complicated component.

**Comment by JakeChampion** [comment]
`@remindme` to look at this before the next quarter, we need to schedule this bigger work as an OKR.

**Comment by chee** [comment]
#100

**Comment by chee** [comment]
https://github.com/financial-times/o-autocomplete
