### ISSUE TITLE
o-cookie-message: focus/tab order does not follow user expectations - ID: DAC_Focus_Order_01

### ISSUE THREAD

**Issue by JakeChampion** [Financial-Times/origami#506]
# Issue
This is from page 41 of the [audit report](https://drive.google.com/file/d/17wq6b0CIX41RA4muBFDzUDxE0-qzHBIH/view)

Issue can be found on: <https://www.ft.com/__origami/service/build/v3/demo?component=o-cookie-message%406.0.1&demo=cookie-message&system_code=origami-repo-data&brand=master>

The focus order is incorrect inside the component, this issue may affect keyboard only users who would expect the focus order to be sequential from top to bottom, left to right.

![screenshot of the demo, with overlays on the focusable elements to show that the focus order is not logical or sequential](https://user-images.githubusercontent.com/1569131/148420264-8766450f-d2ed-40ea-9f4d-f238ac460a2a.png)

# Proposed Solution:
Change the order of the elements in the DOM to ensure that the keyboard focus order is logical and sequential.

**Comment by JakeChampion** [comment]
This issue is also present on <https://www.ft.com/__origami/service/build/v3/demo?component=o-cookie-message%406.0.1&demo=alternative-cookie-message&system_code=origami-repo-data&brand=master> and found on page 48 of the audit report

**Comment by notlee** [comment]
We can fix this by updating markdown and could use `order: -1` on the secondary button to avoid a breaking change
