### ISSUE TITLE
Sync Vault secrets to GitHub/Heroku/AWS/Fastly

### ISSUE THREAD

**Issue by origamiserviceuser** [Financial-Times/origami#51]
Now that we have our secrets in Vault (https://github.com/Financial-Times/origami/issues/31). We can automate the process of populating the same secrets in GitHub/Heroku/etc.

Projects which sync Vault to other places:
https://github.com/Financial-Times/next-vault-sync
https://github.com/Financial-Times/ip-vault-sync

**Comment by JakeChampion** [comment]
Good idea!

**Comment by i-like-robots** [comment]
And another one: https://github.com/Financial-Times/specialist-secrets

**Comment by JakeChampion** [comment]
Let's close this for now, we still don't have capacity for this work and likely can wait for a shared solution to be built which we could use 👍
