### ISSUE TITLE
o-footer-services: Improve link descriptions for use with screen readers - ID: DAC_Information_Displayed_Using_CSS_03

### ISSUE THREAD

**Issue by JakeChampion** [Financial-Times/origami#516]
# Issue
This is from page 73 of the [audit report](https://drive.google.com/file/d/17wq6b0CIX41RA4muBFDzUDxE0-qzHBIH/view)

Issue can be found on: <https://www.ft.com/__origami/service/build/v3/demo?component=o-footer-services@4.0.2&demo=dark-footer&system_code=origami-repo-data&brand=master>

The ‘like this one’ link contains a visual cue for sighted users to inform them that the link opens in a new window, but for screen reader users there is no auditory cue to inform users of this behaviour.

# Proposed Solution:
Add visually hidden text to the link to inform screen reader users that the link opens in a new window.
Example:
 <a class="o-footer-services__content--external" href="/somewhere">like this one</a>
 <a class="o-footer-services__content--external" href="/somewhere">like this one<span class="visually-hidden">(opens in a new window)</span></a>

**Comment by notlee** [comment]
Done. We decided to remove this ambiguous icon. See: https://github.com/Financial-Times/origami/pull/636
