### ISSUE TITLE
o-forms: broken skip link in error summary - ID: DAC_Bypass_Blocks_01

### ISSUE THREAD

**Issue by JakeChampion** [Financial-Times/origami#518]
# Issue
This is from page 77 of the [audit report](https://drive.google.com/file/d/17wq6b0CIX41RA4muBFDzUDxE0-qzHBIH/view)

Issue can be found on: <https://www.ft.com/__origami/service/build/v3/demo?component=o-forms@9.0.1&demo=inverse-form&system_code=origami-repo-data&brand=master#my-date-input>

When the page loads, an error message is already present at the top of the page. The skip link in the error summary has an invalid destination and when users activate the link the focus is not directed to the date input. This issue may affect keyboard only and screen reader users who would expect to activate the link in the summary and be directed to the input where an error had occurred in the form field.
 
# Proposed Solution:
Ensure the link ID matches the ID of the input where the error has occurred, where grouped elements are present and have been left empty, this must be the ID of the first input.
```html
<a href="#my-date-input">
<!-- the name of the invalid input -->
<span class="o-forms__error-summary__item-overview">My date input</span>: <!-- a description of what is wrong and how to fix it -->
<span class="o-forms__error-summary__item-detail">
Please use the format (DD/MM/YYYY)
</span>
</a>
 <input class="o-forms-input__day-part" id="my-date-input" type="text" name="date" value="" pattern="0[1-9]|[12]\d|3[01]" aria-label="Day (DD)" required="">
```

**Comment by notlee** [comment]
Fixed here: https://github.com/Financial-Times/origami/commit/930c1cff88589a1a4e7baef00f53ae54fd7e7d7d
