### ISSUE TITLE
Migrate Origami Fastly Services back into the ft.com-cdn Fastly Service

### ISSUE THREAD

**Issue by JakeChampion** [Financial-Times/origami#52]
This is because we are currently getting charged twice for the bandwidth due to having Origami Fastly Services as backends on the ft.com-cdn Fastly Service.

- [x] image service
- [ ] build service

**Comment by sjparkinson** [comment]
This is the most significant change we can make to reduce the costs on our monthly Fastly bill, so all up for supporting making this happen. Would also be a good chance to get some new engineers working on our configuration.

**Comment by kavanagh** [comment]
Just so I'm clear on this are, we specifically talk about the Image Service and the Build Services?

Where does www.ft.com use the Build Service? Loading fonts and something else?

This solution might be quickest/cheapest to implement. Is it the right one? Should www.ft.com pages go to other domains for its images and fonts?

We can change application code to get images from a new domain and font loading is centralised in one place. What are the tradeoff for doing this? I can think of not benefitting from HTTP2 connection optimisations as a possible downside. On the upside cookieless domains.

Lastly, will this make the ft.com-cdn Fastly service too complex?

**Comment by sjparkinson** [comment]
Jake's raised an initial PR for this at https://github.com/Financial-Times/ft.com-cdn/pull/621.

**Comment by JakeChampion** [comment]
@kavanagh it's not just www.ft.com which uses the image and build service, lots of other ft group products use the services. since the change I've made doesn't change the user-facing domain at all (it was always via www.ft.com), I've gone ahead and merged and released it so that we get the cost savings benefits.

The points around using a cookieless domain are good points to raise. Let's have another issue/ticket for that discussion :-)

**Comment by JakeChampion** [comment]
Final part of this work is here --> https://github.com/Financial-Times/ft.com-cdn/pull/624

**Comment by JakeChampion** [comment]
This work is now done :-)
