### ISSUE TITLE
Move component stylelint configuration into its own repo

### ISSUE THREAD

**Issue by notlee** [Financial-Times/origami#53]
Aims:
- Allow code editors to read stylelint configuration whilst working on a component
- Allow individual Origami components to customise stylelint configuration -- [the spec says](https://origami.ft.com/spec/v1/sass/#syntax-convention) component indent type (tabs or spaces) is not standardised but we now lint for it to prevent a mix, which is common, so customisation is necessary to allow either.
- Allow non-Origami components to use the same configuration, if they wished

Steps:
- Move our [new stylelint configuration](https://github.com/Financial-Times/origami-build-tools/pull/727) into its own repo `stylelint-config-origami-component` like [eslint-config-origami-component](https://github.com/Financial-Times/eslint-config-origami-component).
- Update `obt verify` to use the new `stylelint-config-origami-component`  repo.
- Add stylelint configuration that extends `stylelint-config-origami-component` to every component like we have for [.eslintrc](https://github.com/Financial-Times/o-table/blob/593cdc4be8af4ceddbfebe710c707c1146fcdafa/.eslintrc.js#L2)
- Confirm that obt uses the components stylelint if customised, but verifies like normal if not defined at all by the component
- Update [the spec](https://origami.ft.com/spec/v1/sass/) to say that customised lint config is ok "exceptions may be enabled ~temporarily~ ". Make that part of the sass spec more like the [JS equivalent](https://origami.ft.com/spec/v1/javascript/):
>Developers should stick to the Origami eslintrc config, since this represents a common standard across FT teams. Custom linting may be defined at the component level with a .eslintrc file, or at the file level with a /*eslint ... */ comment.

**Comment by JakeChampion** [comment]
Excellent idea, I agree with this proposal :-)

**Comment by JakeChampion** [comment]
> Steps:
> 
>     * Move our [new stylelint configuration](https://github.com/Financial-Times/origami-build-tools/pull/727) into its own repo `stylelint-config-origami-component` like [eslint-config-origami-component](https://github.com/Financial-Times/eslint-config-origami-component).
> 
>     * Update `obt verify` to use the new `stylelint-config-origami-component`  repo.
> 
>     * Add stylelint configuration that extends `stylelint-config-origami-component` to every component like we have for [.eslintrc](https://github.com/Financial-Times/o-table/blob/593cdc4be8af4ceddbfebe710c707c1146fcdafa/.eslintrc.js#L2)
> 
>     * Confirm that obt uses the components stylelint if customised, but verifies like normal if not defined at all by the component
> 
>     * Update [the spec](https://origami.ft.com/spec/v1/sass/) to say that customised lint config is ok "exceptions may be enabled ~temporarily~ ". Make that part of the sass spec more like the [JS equivalent](https://origami.ft.com/spec/v1/javascript/):

Step 1 is done -- https://github.com/Financial-Times/stylelint-config-origami-component
Step 2 is done -- https://github.com/Financial-Times/origami-build-tools/blob/master/config/.stylelintrc.json
Step 3 is done -- https://github.com/search?l=JavaScript&q=org%3AFinancial-Times+stylelint-config-origami-component&type=Code

We still need to do steps 4 and 5
