### ISSUE TITLE
o-forms: usability issue on date demo - ID: Date_Inputs_01

### ISSUE THREAD

**Issue by JakeChampion** [Financial-Times/origami#536]
# Issue
This is from page 108 of the [audit report](https://drive.google.com/file/d/17wq6b0CIX41RA4muBFDzUDxE0-qzHBIH/view)

Issue can be found on: <https://www.ft.com/__origami/service/build/v3/demo?component=o-forms@9.0.1&demo=date&system_code=origami-repo-data&brand=master>

The invalid / inline date input fields all announce as ‘invalid entry’ when screen reader users enter into them. This may be confusing and more time consuming for screen reader users.

# Screen Reader comments

> Usability comment: Several of the date input fields on this page reported ‘invalid entry’ as part of their error handling. This was confusing because the edit fields contained no data.
> Thus, this announcement may confuse users into thinking that the edit fields are already contain information.
> It would be helpful if such announcements only appeared when errors actually occurred. This would provide confidence to users and ensure accuracy in error reporting.
> Please note that this issue was present with NVDA. And VoiceOver but did not occur to VoiceOver.

 
# Proposed Solution:
Ensure that the date inputs only announce ‘invalid entry’ when the entry is invalid or remove it completely.

**Comment by notlee** [comment]
Better get NVDA set up! ✨
