### ISSUE TITLE
o-header: improve navigation to international edition link for screen reader users - ID: DAC_Information_And_Relationships_01

### ISSUE THREAD

**Issue by JakeChampion** [Financial-Times/origami#547]
# Issue
This is from page 165 of the [audit report](https://drive.google.com/file/d/17wq6b0CIX41RA4muBFDzUDxE0-qzHBIH/view)

Issue can be found on: <https://www.ft.com/__origami/service/build/v3/demo?component=o-header@9.0.1&demo=header&system_code=origami-repo-data&brand=master>

The ‘Switch to International Edition’ link has been contained inside an unordered list, but the list has not been structured correctly. The link has been placed below the `<li></li>` tags in the list. Screen reader users may find difficulty in navigating and identifying the structure of the list correctly as a result.

# Proposed Solution:
In this case, the link can be presented independently of the list and the list can be removed.

**Comment by notlee** [comment]
This has been fixed https://github.com/Financial-Times/origami/pull/327
