### ISSUE TITLE
o-header: update demo link text to not use abbreviations - ID: DAC_Link_Purpose_Link_Only_02

### ISSUE THREAD

**Issue by JakeChampion** [Financial-Times/origami#550]
# Issue
This is from page 168 of the [audit report](https://drive.google.com/file/d/17wq6b0CIX41RA4muBFDzUDxE0-qzHBIH/view)

Issue can be found on: <https://www.ft.com/__origami/service/build/v3/demo?component=o-header-services@5.0.1&demo=drop-down-navigation&system_code=origami-repo-data&brand=master>

The links text ‘DOCS’ and ‘SPECS’ is non-descriptive, and some users may not understand the abbreviations used and the purpose of the links.

# Proposed Solution:
The ‘DOCS’ and ‘SPECS’ links should use the full meaning of the abbreviation to allow all users to identify the purpose of the links for example ‘Documentation’ and ‘Specification’.

**Comment by chee** [comment]
i guess we should also update this on our website ^_^
