### ISSUE TITLE
Link to standard Sass/JS docs from each component.

### ISSUE THREAD

**Issue by notlee** [Financial-Times/origami#59]
Some (most?) of our component READMEs do not explain how to import the 
component Sass module. They also do not consistently document the different
ways  a component's JavaScript can be initialised.

As Jake suggests on [the original issue](https://github.com/Financial-Times/o-lazy-load/issues/32) for this:
>We should likely have a page on origami.ft.com which we link to from every component's readme.md file about how to import and instantiate the JS and the Sass/CSS.

These links are maybe something we could lint for using [remark-preset-lint-origami-component-readme](https://github.com/Financial-Times/remark-preset-lint-origami-component-readme).

**Comment by JakeChampion** [comment]
I agree with this proposal :-D

**Comment by JakeChampion** [comment]
Reminder mainly to myself, ensure we add this to the create-origami-component template also

**Comment by notlee** [comment]
Hmm I think linking to the Build Service and manual build tutotials might be the most helpful way to communicate how to include and initalise Origami components. What do you think to adding this to all components as a starting point @chee @JakeChampion, and linting for the presence of a link to the manual build and build service tutorial?

---------------

There are two ways to include `o-table` in your project, consistent with other Origami components.

The [Origami Build Service](https://origami.ft.com/docs/tutorials/build-service/) is the quickest way to include `o-table`. It delivers CSS and JavaScript which may be included in your project using `link` and `script` tags. 

The second approach is to use a [manual build process](https://origami.ft.com/docs/tutorials/manual-build/). A manual build involves including `o-table` code in your project via Bower or NPM package managers. This approach allows for more customisation compared with the
Origami Build Service.

If you're new to Origami or would like to refresh your memory, see the [Origami Build Service tutorial](https://origami.ft.com/docs/tutorials/build-service/) or the [manual build process tutorial](https://origami.ft.com/docs/tutorials/manual-build/).

<p>Using the Origami Build Service is the quickest way to include `o-table` in your project. The service bundles component <abbr title="Cascading Style Sheets">CSS</abbr> and JavaScript for which can be added to a project using a <code class="language-plaintext highlighter-rouge">link</code> and <code class="language-plaintext highlighter-rouge">script</code> tag.</p>

---------------

![Screenshot 2020-08-06 at 11 55 16](https://user-images.githubusercontent.com/10405691/89524180-03844b00-d7dc-11ea-88b9-6c7426334840.png)

**Comment by notlee** [comment]
Oh! We already have a [page with this content](https://origami.ft.com/docs/components/#including-origami-components-in-your-project). How about this?

-----------

There are two ways to include `o-table` in your project, consistent with other Origami components. See [how
to include Origami components in your project](https://origami.ft.com/docs/tutorials/build-service/).

-----------

![Screenshot 2020-08-06 at 12 15 37](https://user-images.githubusercontent.com/10405691/89525802-ac33aa00-d7de-11ea-9125-2482b9b39d6c.png)

**Comment by JakeChampion** [comment]
> Hmm I think linking to the Build Service and manual build tutotials might be the most helpful way to communicate how to include and initalise Origami components. What do you think to adding this to all components as a starting point @chee @JakeChampion, and linting for the presence of a link to the manual build and build service tutorial?
> 
> There are two ways to include `o-table` in your project, consistent with other Origami components.
> 
> The [Origami Build Service](https://origami.ft.com/docs/tutorials/build-service/) is the quickest way to include `o-table`. It delivers CSS and JavaScript which may be included in your project using `link` and `script` tags.
> 
> The second approach is to use a [manual build process](https://origami.ft.com/docs/tutorials/manual-build/). A manual build involves including `o-table` code in your project via Bower or NPM package managers. This approach allows for more customisation compared with the
> Origami Build Service.
> 
> If you're new to Origami or would like to refresh your memory, see the [Origami Build Service tutorial](https://origami.ft.com/docs/tutorials/build-service/) or the [manual build process tutorial](https://origami.ft.com/docs/tutorials/manual-build/).
> 
> Using the Origami Build Service is the quickest way to include `o-table` in your project. The service bundles component CSS and JavaScript for which can be added to a project using a `link` and `script` tag.
> 
> ![Screenshot 2020-08-06 at 11 55 16](https://user-images.githubusercontent.com/10405691/89524180-03844b00-d7dc-11ea-88b9-6c7426334840.png)

I like it! The specication states components *should not* include generic instructions such as this, which is not an issue because it is not a *must not* 👍  -- https://origami.ft.com/spec/v1/components/#readme

**Comment by notlee** [comment]
[we could cut it down to avoid duplications](https://github.com/Financial-Times/origami/issues/59#issuecomment-669867139) :)

**Comment by JakeChampion** [comment]
> Oh! We already have a [page with this content](https://origami.ft.com/docs/components/#including-origami-components-in-your-project). How about this?
> 
> There are two ways to include `o-table` in your project, consistent with other Origami components. See [how to include Origami components in your project](https://origami.ft.com/docs/tutorials/build-service/).
> 
> ![Screenshot 2020-08-06 at 12 15 37](https://user-images.githubusercontent.com/10405691/89525802-ac33aa00-d7de-11ea-9125-2482b9b39d6c.png)

Good find! We should maybe update that to mention npm as an alternative as well

**Comment by chee** [comment]
yes! i'm a big fan of this, linking out the document :)

**Comment by notlee** [comment]
Hmm I'm not sure we can lint for the link. There are some components where it doesn't make sense such as `o-fonts-assets`, `o-utils`, and `o-autoinit` (I guess the last two are arguable). Each of those examples are in the `utilities` category of component. Maybe we lint for this in non-utility components?

**Comment by notlee** [comment]
All components have the new usage section expect a few cases where it makes sense not to. 
There are other related issues to handle linting for future components:
- lint: https://github.com/Financial-Times/remark-preset-lint-origami-component/issues/13
- lint opt-out for exceptions: https://github.com/Financial-Times/origami-build-tools/issues/875
- new component boilerplate: https://github.com/Financial-Times/create-origami-component/issues/158
And a couple of components with PRs blocked which are being worked on:
- https://github.com/Financial-Times/o-grid/pull/226
- https://github.com/Financial-Times/o-lazy-load/pull/35
