### ISSUE TITLE
Proposal: Proposals in the repo

### ISSUE THREAD

**Issue by chee** [Financial-Times/origami#60]
Our proposal process currently uses issues. These are great, expect there is no distinction in path between an accepted proposal and a rejected proposal. Both of them, the issue gets closed.

Here's my proposal:

Instead of writing proposals up as an issue, let's write them up as a pull request adding a markdown file to a directory called "proposals/accepted" so we can have a satisfying way of saying "Yes" or "No" to a proposal.

We can also move proposals to a `proposals/complete` folder when they are done, adding a note about how the proposal was implemented. Which will be great for documenting what happened after the proposal was accepted.

## benefits

* Easier to see on what we've accepted and are working on!
* Documentation on what what we've done and how we did it.
* Use your own text editor to make the proposal!

## drawbacks

* Maybe it's less easy to create a proposal from outside the team (have to clone the repo, or copy-and-paste template)

## prior art

there is a similar process in the `rfcs` repos of [the npm project](https://github.com/npm/rfcs) and [rustlang](https://github.com/rust-lang/rfcs/#what-the-process-is)

## work required
1. Update the [contribution guide](https://github.com/Financial-Times/origami/blob/master/.github/CONTRIBUTING.md)
2. Move the templates from the `.github/ISSUE_TEMPLATES/` to a `templates/` directory
3. _optional:_ convert old proposals to files in the repo

### nothing
keep what we have

### action
We could keep the issue mechanism around and have an action to automatically create the file in the repo of an accepted issue. we could comment `@origamiserviceuser this is accepted` or something

**Comment by JakeChampion** [comment]
Yes, this is a very good idea, let's do this :-)

**Comment by notlee** [comment]
Yeah I like this idea. Having the proposal under version control in particular; during the major cascade a bunch of proposals were changed based on feedback and it was tricky to record that (do you update the issue body losing the initial proposal, or keep posting an updated version of the whole proposal in an issue comment?). 

> Maybe it's less easy to create a proposal from outside the team (have to clone the repo, or copy-and-paste template)
This is a good point though. It would be a shame to make it more difficult for people outside the team to create a proposal. Maybe we could allude to an issue being ok and have a Origami team member any to a PR?

**Comment by chee** [comment]
yes! i'm fine with us moving them to PRs. I think we could also create a github action that would automatically convert proposal issues to PRs in this repo.

```pseudocode
on new-issue, issue-updated {
  if issue.labels.contains proposal {
    - create file ~/proposals/accepted/0XXX-issue-name-as-slug.md
    - create pr of issue name with this new file
    - add comment to issue saying "this has been automatically converted to a PR! see here: <link>"
    - close issue
  }
 }
```

**Comment by chee** [comment]
> during the major cascade a bunch of proposals were changed based on feedback and it was tricky to record that (do you update the issue body losing the initial proposal, or keep posting an updated version of the whole proposal in an issue comment?).

this is such a great point, having the PR means you also have the changes. And people can provide help as ` ```suggestion ` blocks too.

**Comment by JakeChampion** [comment]
> yes! i'm fine with us moving them to PRs. I think we could also create a github action that would automatically convert proposal issues to PRs in this repo.
> 
> ```
> on new-issue, issue-updated {
>   if issue.labels.contains proposal {
>     - create file ~/proposals/accepted/0XXX-issue-name-as-slug.md
>     - create pr of issue name with this new file and any labels from the issue
>     - add comment to issue saying "this has been automatically converted to a PR! see here: <link>"
>     - close issue
>   }
>  }
> ```

This action is another great idea :-)

I definitely think this is the next proposal we should do, that way all other proposals can use this new system :-)
