### ISSUE TITLE
feature request: toggle button on white background

### ISSUE THREAD

**Issue by notlee** [Financial-Times/origami#702]
For the core brand, toggle buttons work on paper or dark/slate backgrounds.
If used on a white background the toggle is paper which looks strange.

Somehow add support for the toggles on a white button. Suggested approaches:
- Introduce CSS Custom Properties to configurable toggle styles.
- Add a modifier class specifically for use on a white background.

Request from the acquisition team / Ajai. 

<img width="590" alt="Screenshot 2022-04-08 at 13 49 30" src="https://user-images.githubusercontent.com/10405691/162438855-47528626-c610-4278-93b4-90592c6e68db.png">

**Comment by jorbuedo** [comment]
I'm not too familiar with origami yet. Is there any other instance of css custom properties?
My approach would be just having a css variable for the background color, which would be used for the toggle inner circle as well.

**Comment by notlee** [comment]
Thanks for your patience @jorbuedo! Here's a PR which adds a new theme class to use toggles on a white background. https://github.com/Financial-Times/origami/pull/715
