### ISSUE TITLE
Jake: Survey to see how and when the Design team involve Origami (the product and the team) in their design process.

### ISSUE THREAD

**Issue by JakeChampion** [Financial-Times/origami#71]

**Comment by notlee** [comment]
As discussed with Jake I'm not sure a survey is the right tool: There's a bias toward people who are willing/able to respond to a survey and in what detail; it would be easy for us to write poor quantitive questions (e.g. we don't know the different ways designers interact with Origami to ask multiple choice); and a qualitative survey is stilted compared to other research techniques such as an interview or workshop where we can chat, ask clarifying questions, etc.

Instead, how about a semi structured interview? There are ~20 designers so we could interview everyone for ~30mins within a few days work, but will also need some time to map themes and discuss our findings. Its a little time consuming but I think a semi structured interview will do more for our understanding of the design teams process and to improve our relationship with the team compared to a survey. 

Thoughts?

**Comment by chee** [comment]
this issue is taken care of by some ongoing conversations with the design team :)
