### ISSUE TITLE
Update all workflows to work for PRs from forks

### ISSUE THREAD

**Issue by JakeChampion** [Financial-Times/origami#77]
I found out how to make GitHub Workflows work for pull requests from forks!
GitHub added a new trigger pull_request_target.
Here is the explanation of the new trigger:
>This event is similar to pull_request, except that it runs in the context of the base repository of the pull request, rather than in the merge commit. This means that you can more safely make your secrets available to the workflows triggered by the pull request, because only workflows defined in the commit on the base repository are run. For example, this event allows you to create workflows that label and comment on pull requests, based on the contents of the event payload.

I tried it on polyfill-library and it really does work :smile: -- https://github.com/Financial-Times/polyfill-library/actions/runs/213807297
I think we should update all our workflows to use this instead of the trigger pull_request so that forks work.

What do you both think @chee and @notlee?

**Comment by notlee** [comment]
definitely project board / label related workflows! 🎉 I guess not_all_ workflows though, non which depend on checking out the code

**Comment by JakeChampion** [comment]
>I guess not _all_ workflows though, non which depend on checking out the code

Agreed!

**Comment by JakeChampion** [comment]
This was completed via all the referenced pull-requests above 👍
