### ISSUE TITLE
Place the ‘Clear input’ button correctly for improved accessibility

### ISSUE THREAD

**Issue by akomiqaia** [Financial-Times/origami#817]
Place the ‘Clear input’ button for o-autocomplete adjacent to the input field with a visual label which will enable users of assistive technologies to identify and interact with the button correctly. This was suggested from [audit](https://drive.google.com/file/d/17wq6b0CIX41RA4muBFDzUDxE0-qzHBIH/view) on page 14.

**Comment by notlee** [comment]
The clear button is no longer part of the label 👍
