### ISSUE TITLE
write a proposal for a convention-over-configuration demos structure

### ISSUE THREAD

**Issue by chee** [Financial-Times/origami#82]
creating this as a todo item for myself.

something like

```
demos
└── src
    ├── bright-buttons
    │   ├── data.json
    │   ├── readme.md
    │   ├── script.js
    │   ├── style.scss
    │   └── template.mustache
    └── pa11y
        ├── data.json
        ├── hide
        ├── readme.md
        ├── style.scss
        └── template.mustache
```

**Comment by notlee** [comment]
In this propsoal we should maybe explore how this is an exciting opportunity for each demo to have a readme. It could allow us to document components based on usecases, with documentation next to demos and code snippets. At the moment code snippets are repeated in demos and the readme. It can be hard to discuss features in the reame without a demo for reference.

**Comment by chee** [comment]
There's a further option here that the entry-point could be a single `readme.md` or `readme.mdx` file and the demo is written as a document with inline components.

that would give us more freedom in how we write the demos, but less power in how we can display them.

and lee suggested that perhaps we would keep the conventional Sass and JavaScript filenames, so we can show what was in them in tabs. at the moment, we only show the user the html that was used to make a demo, not the sass or js.

i think that in order to explore this one we probably want to go npm-first first.

**Comment by chee** [comment]
maybe a demo should be an npm module? and list the dependencies in `package.json`??!

**Comment by chee** [comment]
Write two specifications!!

* the demo tree
```
o-table/
└── demos
    ├── basic-table
    │   ├── index.html
    │   ├── readme.md
    │   ├── script.js
    │   └── style.sass
    ├── monkey-table
    │   ├── index.html
    │   ├── readme.md
    │   ├── script.js
    │   └── style.sass
    ├── readme.md
    └── sortable-table
        ├── index.html
        ├── readme.md
        ├── script.js
        └── style.sass
```

imagine this

so you have a readme.md inside demos, and when you open up the demo page it shows whatever is in that followed by the content of each of the other readmes

and at the bottom of the other readme content, it shows a codepen-like box

with a tab for each of the index.html,script.js,style.sass and output

(and a little dropdown for opening an individual demo in browserstack in one of our supported browsers)

it's also recursive, so if inside monkey-table you have more directories containing index.html,script.js,style.sass,readme.md

then those will be weaved in under the monkey-table section

and we can also then create navigation based on this. you can either view all the demos on a big page, or navigate in to any sub-demo and view only that (and its sub-demos)

and we can even create a tool that statically generates the whole thing as part of the npm publish

so the registry just opens docs/index.html

* the demo entry point

A specification that components must be published with a `docs/index.html` file that contains documentation and demos.

**Comment by notlee** [comment]
> maybe a demo should be an npm module? and list the dependencies in `package.json`??!

yes! our current demo dependency approach causes problems: https://github.com/Financial-Times/origami-build-tools/issues/906

**Comment by JakeChampion** [comment]
Here is the proposal :-) https://github.com/Financial-Times/origami/pull/90
