### ISSUE TITLE
o-header: user can leave open drawer accidentally and navigate content behind

### ISSUE THREAD

**Issue by notlee** [Financial-Times/origami#902]
When a user of screen reading assistive technologies navigates through the expanded menu using the arrow keys, they are not trapped within the menu and can leave the menu returning to the page. However, this only occurs when navigating back up the page, as the menu has been situated at the end of the DOM. 

*See how we trap focus in o-overlay*

https://docs.google.com/document/d/17-d7DAAORFCaUbiHdFPqvrBerUKbMyhG/edit#bookmark=id.8nyxjz95mzek
https://financialtimes.atlassian.net/browse/CON-2116

![image-20221012-105433](https://user-images.githubusercontent.com/10405691/204035227-5930cd18-2127-4869-88e8-2962ca497d00.png)

**Comment by akomiqaia** [comment]
I am a bit confused about this one. The DAC comment contradicts Screen reader comments. And your comment is about how content is listed. 929f9d1 commit adds aria-labels to listed content so screen readers will announce headings of the list items in the drawer. I could not recreate the issues mentioned about leaving navbar or not. focus seems to be trapped within the drawer and it can be closed by pressing ESC.

**Comment by notlee** [comment]
I've corrected the description of this issue. It was an amalgamation of 2 issues 🙈 The issue here is that navigating the drawer backward using the keyboard (e.g. shift tab) leaves the open drawer and starts navigating the page behind. Focus should stay in the drawer until it's closed. Here's how we do that in o-overlay: https://github.com/Financial-Times/origami/blob/09adefeea8bd8b623da37fe8251fc3b9edbc379a/components/o-overlay/src/js/overlay.js#L346

https://user-images.githubusercontent.com/10405691/205663604-09d39c84-41cc-4d42-a789-3270753be52d.mp4
