### ISSUE TITLE
Let's remove the template rule from the specification

### ISSUE THREAD

**Issue by chee** [Financial-Times/origami#95]
What do you think?

Right now the spec says that components shouldn't have templates, and if they do they must be mustache.

But in reality, we have JavaScript templates. 

Here's one in o-message: https://github.com/Financial-Times/o-message/blob/master/src/js/construct-element.js

here's one in o-cookie message: https://github.com/Financial-Times/o-cookie-message/blob/master/src/js/cookie-message.js#L68-L97

What if, instead of saying "no templates" we say what we mean:

- **Origami components must work without templates**
- **Breaking changes to markup are major changes to the component**

**Comment by notlee** [comment]
👍 yes

**Comment by notlee** [comment]
In the short term it might lead to a slightly confusing world where some components provide jsx templates, some mustache, some template literals, in different places. But I think that is ok to move us forward. We can always recommend/guarantee a specific kind of template/directory structure in the future.

**Comment by JakeChampion** [comment]
Yes, this is a great idea :-)

**Comment by chee** [comment]
> In the short term it might lead to a slightly confusing world where some components provide jsx templates, some mustache, some template literals, in different places. But I think that is ok to move us forward. We can always recommend/guarantee a specific kind of template/directory structure in the future.

That's how I see it! Later we can say that they _must_ provide a specific template type, but it's also not a problem if components continue to provide other templates too. Whatever makes it easier for people to use Origami.

**Comment by chee** [comment]
We did this along with the bathwater
